<?php

namespace MessageBundle\Repository;

/**
 * categstockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categstockRepository extends \Doctrine\ORM\EntityRepository
{
}
