<?php

namespace MessageBundle\Repository;

/**
 * categRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categRepository extends \Doctrine\ORM\EntityRepository
{
}
