<?php

namespace MessageBundle\Repository;

/**
 * messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends \Doctrine\ORM\EntityRepository
{
}
