<?php

namespace MessageBundle\Repository;

/**
 * reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseRepository extends \Doctrine\ORM\EntityRepository
{
}
