<?php

namespace MessageBundle\Repository;

/**
 * stockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockRepository extends \Doctrine\ORM\EntityRepository
{
}
