<?php

namespace ProduitBundle\Repository;

/**
 * PanierProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
