<?php

namespace ProduitBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function trierPrixElv()
    {

        $query = $this->getEntityManager()

            ->createQuery("SELECT v from ProduitBundle:Produits v ORDER BY v.prix DESC ");
        return $query->getResult();

    }
    public function trierPrixBas()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT v from ProduitBundle:Produits v ORDER BY v.prix ASC ");
        return $query->getResult();

    }

    public function likeProduit()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.likes', 'DESC')
            ->getQuery();

        return $query->setMaxResults(3)->getResult();

    }
    public function RechercheTitreProduit($keyWord)
    {
        $query = $this->getEntityManager()->createQuery('SELECT v from ProduitBundle:Produits v WHERE v.nomProd LiKE :val ')
        ->setParameter('val',$keyWord);

        return $query->getResult();

    }
}
