<?php

namespace CampsBundle\Repository;

/**
 * CampsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampsRepository extends \Doctrine\ORM\EntityRepository
{
}
