message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Controller/Front"
    type: annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller"
    type : annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@ProduitBundle/Controller/'
    type: annotation

