
message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Controller/Front"
    type: annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller"
    type : annotation
    prefix:   /
refugies:
    resource: "@RefugiesBundle/Controller"
    type: annotation
    prefix:   /
Camps:
    resource: "@CampsBundle/Controller"
    type: annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@ProduitBundle/Controller/'
    type: annotation
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

