<?php

namespace RefugiesBundle\Repository;

/**
 * RefugiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function trierageElv()
    {

        $query = $this->getEntityManager()

            ->createQuery("SELECT v from RefugiesBundle:Refugies v ORDER BY v.age DESC ");
        return $query->getResult();

    }
    public function trierageBas()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT v from RefugiesBundle:Refugies v ORDER BY v.age ASC ");
        return $query->getResult();

    }
}
