<?php

namespace CauseBundle\Repository;

/**
 * DonneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneurRepository extends \Doctrine\ORM\EntityRepository
{
}
