<?php

namespace EventBundle\Repository;

/**
 * VolontaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolontaireRepository extends \Doctrine\ORM\EntityRepository
{
}
